#########################################################################################################################################################
#########################################################################################################################################################
###                                                                                                                                                   ###
###  #######   #######   #######   #######         #######   #######   #######   #######   #######   #######   #######   #######   #######   #######  ###
###  ##   ##   ##   ##   ##   ##   ##              ##   ##   ##   ##   ##   ##   ##   ##   ##        ##   ##   #######     ###     ##        ##       ###
###  #######   ##   ##   #######   #######         #######   #######   ##   ##   #######   #######   #######     ###       ###     #######   #######  ###
###  ###       #######   ###       #######         ##        ###       ##   ##   ##        #######   ###         ###       ###     #######   #######  ###
###  ## ##     ##   ##   ## ##     ##              ##        ## ##     ##   ##   ##        ##        ## ##       ###       ###     ##             ##  ###
###  ##   ##   ##   ##   ##   ##   #######         ##        ##   ##   #######   ##        #######   ##   ##     ###     #######   #######   #######  ###
###                                                                                                                                                   ###
#########################################################################################################################################################
#########################################################################################################################################################

################
### MENSAJES ###
################

Messages:
  listMessage: '&b[&cPropiedades&b] &eLista de propiedades: '
  notEnoughArgs: '&b[&cPropiedades&b] &eNo has especificado suficientes argumentos.'
  alreadyHasProperty: '&b[&cPropiedades&b] &eEsta propiedad ya está presente en este objeto.'
  noPermission: '&b[&cPropiedades&b] &eNo tienes permiso para hacer esto.'
  propertyAdded: '&b[&cPropiedades&b] &eHas añadido la propiedad %property%.'
  propertyAddedDisc: '&b[&cPropiedades&b] &ePropiedad añadida con éxito.'
  propertyNotPresent: '&b[&cPropiedades&b] &eEsa propiedad no está presente en el objeto.'
  propertyRemoved: '&b[&cPropiedades&b] &ePropiedad %property% eliminada con éxito.'
  propertyGiven: '&b[&cPropiedades&b] &eHas conseguido la propiedad %property% de nivel %level%.'
  cannotRemoveProperty: '&b[&cPropiedades&b] &eEsa propiedad no puede ser eliminada.'
  addParams: '&b[&cPropiedades&b] &eEl uso es /rareproperties add <Propiedad> <Nivel> <Código de color>.'
  removeParams: '&b[&cPropiedades&b] &eEl uso es /rareproperties remove <Propiedad>.'
  getParams: '&b[&cPropiedades&b] &eEl uso es /rareproperties get <Propiedad> <Nivel>'
  giveParams: '&b[&cPropiedades&b] &eEl uso es /rareproperties give <Jugador> <Propiedad> <Nivel>.'
  giveRandomParams: '&b[&cPropiedades&b] &eEl uso es /rareproperties giveRandom <Jugador> <Propiedad>'
  cannotTeleport: '&b[&cPropiedades&b] &eNo se puede teletransportar a un bloque opaco.'
  captureSuccess: '&b[&cPropiedades&b] &eCaptura te ha dado un huevo.'
  notEnoughHealth: '&b[&cPropiedades&b] &eNo tienes suficiente vida para sacrificar.'
  reload: '&b[&cPropiedades&b] &eEl plugin se ha recargado con éxito.'
  socketGiven: '&b[&cPropiedades&b] &eHas conseguido una Runa Valknut.'
  tomeGiven: '&b[&cPropiedades&b] &eHas conseguido un &5Libro de runas&e.'
  limited: '&b[&cPropiedades&b] &eHas llegado al límite de propiedades en este objeto %permission%/%limit%.'
  help:
    - "&b/rareproperties &eMuestra esta página."
    - "&b/rareproperties list &eMuestra todas las propiedades."
    - "&b/rareproperties add <Propiedad> <Nivel> <Código de color> &eAñade la propiedad al objeto en la mano."
    - "&b/rareproperties remove <Propiedad> &eElimina la propiedad del objeto en la mano."
    - "&b/rareproperties get <Propiedad> <Nivel> &eDa un &dFavor de Sindri&e."
    - "&b/rareproperties give <Jugador> <Propiedad> <Nivel> &eDa un &dFavor de Sindri&e a un jugador."
    - "&b/rareproperties giveRandom <Jugador> <Propiedad> &eDa un &dFavor de Sindri&e a un jugador."
    - "&b/rareproperties socket [color] &eDa una Runa Valknut."
    - "&b/rareproperties tome &eDa un &5Libro de runas&e."
    - "&b/rareproperties showItem &eComando de debug para ver el objeto de la mano."
    - "&b/rareproperties reload &eRecarga la configuración del plugin."
    - "&b"
    - "&eLeyenda: <> Obligatorio  [] Opcional"

###############
### OBJETOS ###
###############

SindrisFavour:
  material: MUSIC_DISC_5
  name: "&d&lFavor de Sindri"
  lore:
    - "&7"
    - "&7Sindri te hará el favor de mejorar"
    - "&7tu objeto con la propiedad mágica de"
  property: "&d%property% %level%"

Socket:
  material: AMETHYST_SHARD
  name: "&lRuna Valknut"
  lore:
    - "&7"
    - "&7Los antiguos Aësir usaban esta"
    - "&7runa en su equipamiento durante"
    - "&7los tiempos de guerra."
  colors:
    - BLUE
    - RED
    - GREEN

IdentifierTome:
  material: WRITTEN_BOOK
  author: yuxputa
  name: "&5&lLibro de runas"
  lore:
    - "&7"
    - "&7Libro que contiene un diccionario"
    - "&7de runas mágicas usadas por los"
    - "&7dioses para identificar objetos"
    - "&7perdidos en el tiempo."

RareItems:
  materials:
    armorMaterial:
      - LEATHER_HELMET
      - LEATHER_CHESTPLATE
      - LEATHER_LEGGINGS
      - LEATHER_BOOTS
      - CHAINMAIL_HELMET
      - CHAINMAIL_CHESTPLATE
      - CHAINMAIL_LEGGINGS
      - CHAINMAIL_BOOTS
      - IRON_HELMET
      - IRON_CHESTPLATE
      - IRON_LEGGINGS
      - IRON_BOOTS
      - GOLDEN_HELMET
      - GOLDEN_CHESTPLATE
      - GOLDEN_LEGGINGS
      - GOLDEN_BOOTS
      - DIAMOND_HELMET
      - DIAMOND_CHESTPLATE
      - DIAMOND_LEGGINGS
      - DIAMOND_BOOTS
      - TURTLE_HELMET
    weaponMaterial:
      - WOODEN_SHOVEL
      - WOODEN_PICKAXE
      - WOODEN_AXE
      - WOODEN_HOE
      - WOODEN_SWORD
      - STONE_SHOVEL
      - STONE_PICKAXE
      - STONE_AXE
      - STONE_HOE
      - STONE_SWORD
      - IRON_SHOVEL
      - IRON_PICKAXE
      - IRON_AXE
      - IRON_HOE
      - IRON_SWORD
      - GOLDEN_SHOVEL
      - GOLDEN_PICKAXE
      - GOLDEN_AXE
      - GOLDEN_HOE
      - GOLDEN_SWORD
      - DIAMOND_SHOVEL
      - DIAMOND_PICKAXE
      - DIAMOND_AXE
      - DIAMOND_HOE
      - DIAMOND_SWORD
      - FISHING_ROD
      - FLINT_AND_STEEL
      - SHEARS
      - SHIELD
      - BOW
      - CROSSBOW

################
### PERMISOS ###
################

Permissions:
  - "rareproperties.limit.5"
  - "rareproperties.limit.4"
  - "rareproperties.limit.3"
  - "rareproperties.limit.2"
  - "rareproperties.limit.1"

#####################
### CONFIGURACIÓN ###
#####################

ConfigValues:
  specialMobChance: 4
  sockettedItemChance: 10
  maxSockets: 3
  unidentifiedChance: 2
  blacklistedWorlds:
    - Halloween

###############
### RAREZAS ###
###############

Rarities:
  Properties:
    Mythic:
      name: "Mítico"
      color: "&d"
      weight: 0
      properties:
        - "Égida"
        - "Andanada"
        - "Captura"
        - "Demolición"
        - "Vuelo"
        - "Presteza"
        - "Propulsion"
        - "Reforzado"
        - "Reparación"
        - "Teletransporte"
        - "Sanación"
        - "Adrenalina"
    Legendary:
      name: "Legendario"
      color: "&6"
      weight: 5
      properties:
        - "Solem"
        - "Noctis"
        - "Armadura"
    Epic:
      name: "Épico"
      color: "&5"
      weight: 25
      properties:
        - "Vampirismo"
        - "Puñalada"
        - "Crítico"
    Rare:
      name: "Raro"
      color: "&9"
      weight: 60
      properties:
        - "Electro"
        - "Corte"
        - "Putrefacción"
        - "Descomposición"
    Uncommon:
      name: "Poco común"
      color: "&a"
      weight: 120
      properties:
        - "Ígneo"
        - "Gélido"
    Common:
      name: "Común"
      color: "&f"
      weight: 200
      properties:
        - "Explosión"
        - "Encogimiento"
        - "Agrandamiento"
  Items:
    Supreme:
      maxEnchants: 10
      minEnchants: 5
      maxEnchantLevel: 10
      maxProperties: 4
      color: "&c&l&n"
      weight: 1
    Divine:
      maxEnchants: 8
      minEnchants: 3
      maxEnchantLevel: 8
      maxProperties: 3
      color: "&f&l&n"
      weight: 5
    Mythic:
      maxEnchants: 6
      minEnchants: 3
      maxEnchantLevel: 7
      maxProperties: 2
      color: "&d&n"
      weight: 15
    Legendary:
      maxEnchants: 5
      minEnchants: 2
      maxEnchantLevel: 6
      maxProperties: 2
      color: "&6&n"
      weight: 45
    Epic:
      maxEnchants: 4
      minEnchants: 2
      maxEnchantLevel: 4
      maxProperties: 1
      color: "&5&n"
      weight: 135
    Rare:
      maxEnchants: 3
      minEnchants: 1
      maxEnchantLevel: 3
      maxProperties: 1
      color: "&9&n"
      weight: 405
    Uncommon:
      maxEnchants: 2
      minEnchants: 1
      maxEnchantLevel: 2
      maxProperties: 0
      color: "&a&n"
      weight: 1215
    Common:
      maxEnchants: 1
      minEnchants: 0
      maxEnchantLevel: 1
      maxProperties: 0
      color: "&b&n"
      weight: 3645

###################
### PROPIEDADES ###
###################

Properties:
  Fly:
    baseCost: 8
    time: 5
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Gasta comida permitiendo volar."
      - "&7&oSolo funciona en armadura o un objeto"
      - "&7&oen la mano primaria o secundaria."
  Repair:
    baseCost: 10
    repairPercentage: 10
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Gasta comida permitiendo reparar el"
      - "&7objeto de la primera posición."
  Burst:
    baseCost: 11
    baseVelocity: 2
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Gasta comida permitiendo enviar"
      - "&7a volar a las entidades cercanas."
  Teleport:
    baseCost: 1
    extraBlocksPerLevel: 2
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Gasta comida permitiendo teletransportarte"
      - "&7hacia donde estés mirando."
  Capture:
    maxProbability: 10000
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Permite conseguir huevos de entidades"
      - "&7al matarlas con una pequeña posibilidad."
  Reinforced:
    baseProbability: 5
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Permite no gastar usos al objeto al"
      - "&7que se pone con una probabilidad."
  Aegis:
    resistanceLevel: 2
    absortionLevel: 2
    sizeMultiplier: 1.5
    effectsDuration: 60
    healthCost: 10
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Sacrifica vida obteniendo resistencia,"
      - "&7absorción y un aumento de tamaño."
  Demolition:
    baseDamage: 15
    baseRange: 4
    foodCost: 5
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Gasta comida permitiendo hacer un golpe"
      - "&7en área de gran poder que además empuja."
  Promptness:
    speedLevel: 1
    sizeMultiplier: 0.6
    effectsDuration: 60
    healthCost: 7
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Sacrifica vida obteniendo velocidad"
      - "&7y una disminución de tamaño."
  Propulsion:
    baseImpulse: 2
    foodCost: 10
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Gasta comida permitiendo elevarte"
      - "&7en el aire como un cohete."
  Healing:
    foodCost: 14
    healthPercent: 5
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Gasta comida permitiendo curarte"
      - "&7un porcentaje de tu vida."
  Adrenaline:
    strengthLevel: 6
    poisonLevel: 2
    sizePerLevel: 0.1
    durationPerLevelStrength: 12
    durationPerLevelPoison: 6
    sound: "ENTITY_WOLF_GROWL"
    soundOff: "ENTITY_WOLF_PANT"
    healthCost: 5
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Sacrifica vida obteniendo fuerza,"
      - "&7veneno y un aumento de tamaño."
  Solem:
    damagePercent: 0.2
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Si es de día harás cada vez más"
      - "&7daño hasta el mediodía."
  Noctis:
    damagePercent: 0.2
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Si es de noche harás cada vez más"
      - "&7daño hasta la medianoche."
  Armor:
    reductionPercent: 0.025
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Otorga mitigación de daño al ser golpeado."
      - "&7&oSolo funciona en armadura."
  Vampirism:
    healthSteal: 0.01
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Al golpear te curarás una parte del daño."
  Backstab:
    extraDamage: 0.1
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Al golpear por la espalda harás más daño."
  Critic:
    extraDamage: 0.2
    chancePerLevel: 1
    sound: "ENTITY_ZOMBIE_ATTACK_IRON_DOOR"
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Probabilidad de hacer daño extra."
  Electro:
    damagePerLevel: 2
    chancePerLevel: 7
    sound: "ITEM_TRIDENT_THUNDER"
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Probabilidad de lanzar un rayo que"
      - "&7no destruye objeto y hace daño."
  Cut:
    damagePerLevel: 1
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Añadirá daño extra a tus ataques."
  Wither:
    modifierPerLevel: 1
    duration: 5
    chancePerLevel: 5
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Probabilidad de infligir wither al golpear."
  Poison:
    modifierPerLevel: 1
    duration: 5
    chancePerLevel: 6
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Probabilidad de infligir veneno al golpear."
  Fire:
    timePerLevel: 2
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Incendiará a los enemigos al golpearlos."
  Freezee:
    chancePerLevel: 7
    damage: 3
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Congelará a los enemigos al golpearlos"
      - "&7y les hará un poco de daño."
  Explosion:
    chancePerLevel: 5
    damage: 2
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Al golpear a los enemigos les hará un"
      - "&7poco de daño e invocará un cohete."
  Shrink:
    chancePerLevel: 1
    durationPerLevel: 3
    sound: "BLOCK_TRIAL_SPAWNER_ABOUT_TO_SPAWN_ITEM"
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Al golpear a los enemigos tendrá la"
      - "&7posibilidad de hacer a los enemigos"
      - "&7más pequeños por un tiempo."
  Enlarge:
    chancePerLevel: 1
    durationPerLevel: 3
    sound: "BLOCK_TRIAL_SPAWNER_ABOUT_TO_SPAWN_ITEM"
    description:
      - "&7"
      - "&7&nDescripción:"
      - "&7Al golpear a los enemigos tendrá la"
      - "&7posibilidad de hacer a los enemigos"
      - "&7más grandes por un tiempo."